name: BMI_deployment

env:
  AZ_WEBAPP_NAME: cd-bmicalculator
  AZ_WEBAPP_PACKAGE_PATH: 'publish'
  UNIT_TEST: 'bp\UnitTest.sln'

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Build Application
      run: dotnet build bp/BPCalculator --configuration Release

    - name: unit tests
      run: dotnet test bp/testing/unitTestProj.csproj --configuration Release --logger "trx;LogFileName=test-results.trx" || true

    - name: Publish Unit Test Results
      uses: dorny/test-reporter@v1
      with:
        name: DotNet Tests                  
        path: '**/test-results.trx'
        reporter: 'dotnet-trx'  
    
    - name: Publish
      run: dotnet publish -c Release -o '${{ env.AZ_WEBAPP_PACKAGE_PATH }}/myapp'