name: deploy-staging-container

env: 
  AZ_WEBAPP_PACKAGE_PATH: 'bp/publish' 

on:
    workflow_run:
        workflows: ["compile-and-test-staging"]
        types: [completed]
        branches: 
          - 'staging'

jobs:
  docker_build_push_acr:
    name: 'Docker Build and Push to ACR'
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Build Application
      run: dotnet build bp/BPCalculator --configuration Release

    - name: Publish
      run: dotnet publish bp/BPCalculator/BPCalculator.csproj -c Release -o '${{ env.AZ_WEBAPP_PACKAGE_PATH }}/myapp'

###### Be aware that the following plugin requires the use of the admin user and does not support service principals
    - name: Login to ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR }}
        username: ${{ secrets.ACR_USER }}
        password: ${{ secrets.ACR_SECRET }}
    - run: |
          docker build . -t ${{ secrets.ACR }}/bpcalculator-staging:${{ github.sha }}
          docker push ${{ secrets.ACR }}/bpcalculator-staging:${{ github.sha }}

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZ_CREDENTIALS }}

    - name: 'Deploy to Azure Container Instances'
      uses: 'azure/aci-deploy@v1'
      with:
        resource-group: ${{ secrets.RG }}
        dns-name-label: cdillon-bpcalc-staging
        image: ${{ secrets.ACR }}/bpcalculator-staging:${{ github.sha }}
        registry-login-server: ${{ secrets.ACR }}
        registry-username: ${{ secrets.ACR_USER }}
        registry-password: ${{ secrets.ACR_SECRET }}
        name: bpcalculator-staging
        location: 'north europe'