name: deploy-container

env: 
  AZ_WEBAPP_PACKAGE_PATH: 'publish' 

on:
  push:
    branches:
      - staging

jobs:
  docker_build_push_acr:
    name: 'Docker Build and Push to ACR'
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Build Application
      run: dotnet build bp/BPCalculator --configuration Release

    - name: Publish
      run: dotnet publish bp/BPCalculator/BPCalculator.csproj -c Release -o '${{ env.AZ_WEBAPP_PACKAGE_PATH }}/myapp'

    - name: Login to ACR
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.ACR }}
        username: ${{ secrets.ARM_CLIENT_ID }}
        password: ${{ secrets.ARM_CLIENT_SECRET }}
 
    - name: Build and push to ACR
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ secrets.STAGING_CONTAINER_NAME }}

    - name: 'Deploy to Azure Container Instances'
      uses: 'azure/aci-deploy@v1'
      with:
        resource-group: ${{ secrets.RG }}
        dns-name-label: ${{ secrets.RG }}${{ github.run_number }}
        image: ${{ secrets.ACR }}/sampleapp:${{ github.sha }}
        registry-login-server: ${{ secrets.ACR }}
        registry-username: ${{ secrets.ARM_CLIENT_ID }}
        registry-password: ${{ secrets.ARM_CLIENT_SECRET }}
        name: bpcalculator-staging
        location: 'north europe'