name: deploy-container
 
on:
  push:
    branches:
      - staging

jobs:
  docker_build_push_acr:
    name: 'Docker Build and Push to ACR'
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to ACR
      uses: docker/login-action@v3
      with:
        login-server: ${{ secrets.ACR }}
        username: ${{ secrets.ARM_CLIENT_ID }}
        password: ${{ secrets.ARM_CLIENT_SECRET }}
 
    - name: Build and push to ACR
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ secret.STAGING_CONTAINER_NAME }}

