name: deploy-staging-container

env: 
  AZ_WEBAPP_PACKAGE_PATH: 'bp/publish' 

on:
    workflow_run:
        workflows: ["compile-and-test-staging"]
        types: [completed]
        branches: 
          - 'staging'

jobs:
  docker_build_push_acr:
    name: 'Docker Build and Push to ACR'
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Build Application
      run: dotnet build bp/BPCalculator --configuration Release

    - name: Publish
      run: dotnet publish bp/BPCalculator/BPCalculator.csproj -c Release -o '${{ env.AZ_WEBAPP_PACKAGE_PATH }}/myapp'

###### Be aware that the following plugin requires the use of the admin user and does not support service principals
    - name: Login to ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR }}
        username: ${{ secrets.ACR_USER }}
        password: ${{ secrets.ACR_SECRET }}
    - run: |
          docker build . -t ${{ secrets.ACR }}/bpcalculator-staging:${{ github.sha }}
          docker push ${{ secrets.ACR }}/bpcalculator-staging:${{ github.sha }}

#    - name: Azure login
#      uses: azure/login@v1
#      with:
#        creds: ${{ secrets.AZ_CREDENTIALS }}
#
#    - name: 'Deploy to Azure Container Instances'
#      uses: 'azure/aci-deploy@v1'
#      with:
#        resource-group: ${{ secrets.RG }}
#        dns-name-label: cdillon-bpcalc-staging
#        image: ${{ secrets.ACR }}/bpcalculator-staging:${{ github.sha }}
#        registry-login-server: ${{ secrets.ACR }}
#        registry-username: ${{ secrets.ACR_USER }}
#        registry-password: ${{ secrets.ACR_SECRET }}
#        name: bpcalculator-staging
#        location: 'north europe'
  terraform:
    name: Plan / Apply
    runs-on: ubuntu-latest
    needs: docker_build_push_acr
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      TF_VAR_rg: ${{ secrets.RG }}
      TF_VAR_STORAGE_ACCOUNT: ${{ secrets.STORAGE_ACCOUNT }}
      TF_VAR_CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
      TF_VAR_tenant: ${{ secrets.ARM_TENANT_ID }}
      TF_VAR_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      TF_VAR_acr_user: ${{ secrets.ACR_USER }}
      TF_VAR_acr_pass: ${{ secrets.ACR_SECRET }}
      TF_VAR_acr_image: ${{ secrets.ACR }}/bpcalculator-staging:${{ github.sha }}
    defaults:
      run:
        working-directory: tf-staging
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Use Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      id: init
      run: terraform init
      continue-on-error: false

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
      continue-on-error: false

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color -input=false
      continue-on-error: false

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false
      continue-on-error: false