name: puppeteer-e2e
on:
    workflow_run:
        workflows: ["zap-scan"]
        types: [completed]
        branches: 
          - 'staging'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3


      - uses: actions/checkout@v3
      - name: Puppeteer test
        uses: tj-actions/puppeteer@v5
        id: puppeteer
        with:
          files: |
            puppeteer/staging-test.js

      - name: Open Pull Request
        if: success()
        run: |
          gh pr create --base main --head staging --title "Merge Staging to Main" --body "Successful staging deployment, merge to main."
