name: staging-tf-validation

env:
  TF_VAR_subscription: terraform.secrets.TF_VAR_SUBSCRIPTION
  TF_VAR_tenant: terraform.secrets.TF_VAR_TENANT
  TF_VAR_rg: terraform.secrets.TF_VAR_RG


on:
  push:
    branches:
      - staging

jobs:
  deploy:
    name: Plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tf-deploy
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Terraform 
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color -input=false
