name: zap-scan
on:
    workflow_run:
        workflows: ["compile-and-test-staging"]
        types: [completed]
        branches: 
          - 'staging'

jobs:
  zap-secuity-test:
    name: zap security test
    runs-on: ubuntu-latest
    environment: staging
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: ZAP security scan
      uses: zaproxy/action-baseline@v0.10.0
      #### Use continue on error because container exits with code 2 if issues are found
      continue-on-error: true
      with:
        target: 'http://cdillon-bpcalc-staging.northeurope.azurecontainer.io'
