name: zap-scan
on:
    workflow_run:
        workflows: ["compile-and-test-staging"]
        types: [completed]
        branches: 
          - 'staging'

jobs:
  zap-secuity-test:
    name: zap security test
    runs-on: ubuntu-latest
    environment: staging
    steps:
    - name: Run local k6 test
      uses: zaproxy/action-baseline@v0.10.0
      with:
        target: 'http://cdillon-bpcalc-staging.northeurope.azurecontainer.io'
